package product;

import java.io.Serializable;

public class Game implements Product, Serializable
{
	private static final long serialVersionUID = 1L;
	
	private int id;
	private String name;
	private double purchasePrice;
	private double sellPrice;
	private int quantity;
	private String description;
	
	/**Constructor, creates a serializable Game object with the given parameters
	 *@author Richmond Liang
	 *@param id generated by the ProductList
	 *@param name name of the game
	 *@param purchasePrice how much the seller bought the game for
	 *@param sellPrice how much the customer pays for the game
	 *@param desc Description of the game
	 *@postcondition new game created
	 */
	public Game(int id, String name, double purchasePrice, double sellPrice, String desc)
	{
		this.id = id;
		this.name = name;
		this.purchasePrice = purchasePrice;
		this.sellPrice = sellPrice;
		quantity = 0;
		description = desc;
	}
	
	///Getters
	@Override
	public int getId() 
	{
		return id;
	}
	@Override
	public String getName() 
	{
		return name;
	}
	@Override
	public double getPurchasePrice() 
	{
		return purchasePrice;
	}
	@Override
	public double getSellPrice() 
	{
		return sellPrice;
	}
	@Override
	public int getQuantity() 
	{
		return quantity;
	}
	@Override
	public String getDescription() 
	{
		return description;
	}
	///Setters
	@Override
	public void setName(String name) 
	{
		this.name = name;
	}

	@Override
	public void setSellPrice(double price) 
	{
		sellPrice = price;
	}
	
	@Override
	public void setPurchasePrice(double price) 
	{
		purchasePrice = price;
	}
	@Override
	public void setDescription(String desc) 
	{
		description = desc;
	}
	
	///Called when the seller buys more of the product
	@Override
	public void buyQuantity(int amount) 
	{
		quantity += amount;
	}
	///Called when the customer buys the product
	@Override
	public void sellQuantity(int amount) 
	{
		quantity -= amount;
	}
	///Called when quantity is editted
	@Override
	public void setQuantity(int amount) 
	{
		quantity = amount;
	}
	
	//Equals
	@Override
	public boolean equals(Object o)
	{
		if(this == o)
		{
			return true;
		}
		else if(o == null || o.getClass() != this.getClass())
		{
			return false;
		}
		Game obj = (Game) o;
		return (this.id == obj.getId() && this.name.equals(obj.getName()));
	}
	
	//hashcode
	public int hashCode()
	{
		return Integer.hashCode(getId()) + getName().hashCode();
	}

}
